version: '3.9'

services:
  portfolio:
    image: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "7070:8080"
    networks:
      - portfolio

networks:
  portfolio:
    name: portfolio
    driver: bridge